# named volume 'portainer_data' is marked as "external" (used by service 'portainer-ce'), so either remove "external" from volume definition or it needs to be created using: docker volume create portainer_data

# Set WG_PASSWORD environment variable in .env file.

name: thk-homelab
services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest' 
    container_name: nginxproxymanager
    restart: always 
    ports:
      - '80:80'
      - '443:443' 
    volumes:
      - /var/lib/docker/volumes/nginx/data:/data
      - /var/lib/docker/volumes/nginx/letsencrypt:/etc/letsencrypt

  portainer-ce:
      container_name: portainer
      restart: always
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
      image: portainer/portainer-ce:lts

  wg-easy:
    container_name: wg
    environment:
        - WG_HOST=vpn.thekornel.ddns.net
        - PASSWORD=${WG_PASSWORD}
        - WG_PORT=52151
    volumes:
        - /wg-easy:/etc/wireguard
    ports:
        - 51820:51820/udp
        - 51821:51821/tcp
    cap_add:
        - NET_ADMIN
        - SYS_MODULE
    sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv4.ip_forward=1
    restart: always
    image: weejewel/wg-easy
volumes:
    portainer_data:
        external: true
        name: portainer_data
